# Generated by Django 2.2.7 on 2019-11-20 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=150)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(default=datetime.datetime(2019, 11, 20, 18, 32, 47, 682488, tzinfo=utc))),
            ],
        ),
    ]
